const OMNILAUNCH_FACTORY_ADDRESS_SEPOLIA =
  "0xbf18924bf9F40B7db77BDea102CD1a84927b7b49";
const OMNILAUNCH_FACTORY_ADDRESS_MUMBAI = "";
const OMNILAUNCH_FACTORY_ADDRESS_ZKEVM =
  "0xcfA60a381A717D4368f704a30C04102125563B15";
const OMNILAUNCH_FACTORY_ADDRESS_ARB = "";
const OMNILAUNCH_FACTORY_ADDRESS_FVM = "";
const OMNILAUNCH_FACTORY_ADDRESS_SCROLL = "";
const OMNILAUNCH_FACTORY_ADDRESS_MANTLE = "";
const OMNILAUNCH_FACTORY_ADDRESS_CELO = "";
const OMNILAUNCH_FACTORY_ADDRESS_BASE = "";
const OMNILAUNCH_FACTORY_ADDRESS_XDC = "";
const OMNILAUNCH_FACTORY_ADDRESS_ZETA = "";
const OMNILAUNCH_FACTORY_ADDRESS_X1 = "";
const OMNILAUNCH_FACTORY_ADDRESS_LINEA = "";

const ADDR_MAP = {
  11155111: OMNILAUNCH_FACTORY_ADDRESS_SEPOLIA,
  80001: OMNILAUNCH_FACTORY_ADDRESS_MUMBAI,
  1442: OMNILAUNCH_FACTORY_ADDRESS_ZKEVM,
  421613: OMNILAUNCH_FACTORY_ADDRESS_ARB,
  314159: OMNILAUNCH_FACTORY_ADDRESS_FVM,
  534351: OMNILAUNCH_FACTORY_ADDRESS_SCROLL, //
  5001: OMNILAUNCH_FACTORY_ADDRESS_MANTLE, //
  84531: OMNILAUNCH_FACTORY_ADDRESS_BASE,
  51: OMNILAUNCH_FACTORY_ADDRESS_XDC, //
  7001: OMNILAUNCH_FACTORY_ADDRESS_ZETA, //
  195: OMNILAUNCH_FACTORY_ADDRESS_X1,
  59140: OMNILAUNCH_FACTORY_ADDRESS_LINEA,
  44787: OMNILAUNCH_FACTORY_ADDRESS_CELO,
};

module.exports = {
  OMNILAUNCH_FACTORY_ADDRESS_SEPOLIA,
  OMNILAUNCH_FACTORY_ADDRESS_MUMBAI,
  OMNILAUNCH_FACTORY_ADDRESS_ZKEVM,
  OMNILAUNCH_FACTORY_ADDRESS_ARB,
  OMNILAUNCH_FACTORY_ADDRESS_FVM,
  OMNILAUNCH_FACTORY_ADDRESS_SCROLL,
  OMNILAUNCH_FACTORY_ADDRESS_MANTLE,
  OMNILAUNCH_FACTORY_ADDRESS_BASE,
  OMNILAUNCH_FACTORY_ADDRESS_XDC,
  OMNILAUNCH_FACTORY_ADDRESS_ZETA,
  OMNILAUNCH_FACTORY_ADDRESS_X1,
  OMNILAUNCH_FACTORY_ADDRESS_LINEA,
  ADDR_MAP,
};
